# ------------------------------------------------
#                     EnxTest
#                 Por Pedro Lucas
# ------------------------------------------------

custom-windcharge: true
# Configuravel no arquivo "wind-config.yml"

database:
  host: localhost
  port: 3306
  database: database
  username: root
  password: ""
