name: EnxTest
version: '1.0'
main: com.pedrorok.enx.Main
api-version: '1.21'
authors: [ Pedro ]
website: pedrorok.com
commands:
  enx:
    description: Comando principal do plugin
    usage: /enx
  home:
    description: Comando para ir para a home
    usage: /home
